name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p ~/.ssh
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          git config --global user.email "auorwi@gmail.com"
          git config --global user.name "auorwei"
          git clone git@github.com:${{ secrets.GH_PAGES_REPO }} public
          rsync -av --delete --exclude='.git' ./ public/ || true
          cd public
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push
